spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://koundb.cvrwbkhznvql.ap-northeast-2.rds.amazonaws.com:3306/kounDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Est1!cebe
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2cf364356a3329e6b0fca033d6447fbd
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true




logging:
  level:
    org.hibernate.SQL: debug




  spring:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb # H2 메모리 데이터베이스 사용
      username: sa
      password:
    h2:
      console:
        enabled: true # H2 콘솔 활성화
    jpa:
      hibernate:
        ddl-auto: update # 데이터베이스 스키마 자동 업데이트 (create 또는 update 중 선택)

  # 다른 설정들...

  logging:
    level:
      org.hibernate.SQL: debug






#logging:
#  level:
#    root: DEBUG
#  file:
#    name: logs/app.log



#
##배포용
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://koundb.cvrwbkhznvql.ap-northeast-2.rds.amazonaws.com:3306/kounDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: Est1!cebe
#
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      hibernate:
#        format_sql: true
#
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#
#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 2cf364356a3329e6b0fca033d6447fbd
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/loginRedirect
#            client-authentication-method: post
#            scope:
#              - profile_nickname
#              - account_email
#        provider:
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id
#
#



